services:
  - type: web
    name: resolve-mais
    runtime: node
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    
    envVars:
      - key: PORT
        value: 5000